### ISSUE TITLE
RequireJS-Knockout 16.2 example does not work

### ISSUE THREAD

**Issue by GoshaFighten** [DevExpress/devextreme-examples#7]
In this line: [https://github.com/DevExpress/devextreme-examples/blob/16_2/requirejs-knockout/index.html#L21](https://github.com/DevExpress/devextreme-examples/blob/16_2/requirejs-knockout/index.html#L21), `node_modules/devextreme` should be replaced with `devextreme_amd`. But, this still gives errors in the console:

`Script error for "devextreme/ui/selection/selection.strategy.deferred.js", needed by: devextreme/ui/selection/selection`

`Script error for "devextreme/ui/selection/selection.strategy.standard.js", needed by: devextreme/ui/selection/selection`

My `package.json`:

``` JSON
{
  "name": "devextreme-requirejs-knockout",
  "version": "1.0.0",
  "description": "DevExtreme with RequireJS and Knockout example",
  "dependencies": {
    "devextreme": "~16.2.3",
    "r.js": "^1.0.3",
    "requirejs": "^2.3.2",
    "jquery": "^3.1.0",
    "knockout": "^3.4.0"
  },
  "scripts": {
    "postinstall": "r_js -convert node_modules/devextreme devextreme_amd"
  },
  "author": "DevExpress",
  "license": "MIT"
}
```

**Comment by kvet** [comment]
This issue will be fixed with the next `devextreme` package release. Please bear with us.
